blank_issues_enabled: false
contact_links:
  - name: Questions & Help
    url: https://github.com/atelier-socle/podcast-feed-maker-vapor/discussions
    about: Ask questions and get help from the community
